# Generated by Django 4.1.7 on 2023-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_user',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس شخص'),
        ),
    ]
