# Generated by Django 4.1.4 on 2023-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(default='url_title', max_length=200, verbose_name='نام در آدرس'),
            preserve_default=False,
        ),
    ]
