# Generated by Django 4.1.7 on 2023-04-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_contact_us_image_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='image',
        ),
    ]
