# Generated by Django 4.1.7 on 2023-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='عکس محصولات '),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
