# Generated by Django 4.1.4 on 2023-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productbrand_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image', upload_to='images/products', verbose_name='عکس محصولات '),
            preserve_default=False,
        ),
    ]
