# Generated by Django 4.1.7 on 2023-05-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(verbose_name='لینک'),
        ),
    ]
